server:
  env: dev
  name: bosh-admin
  url: 127.0.0.1
  port: 8081

log:
  rootDir: ./logs
  format: json
  timestampFormat: '2006-01-02 15:04:05.000'
  maxBackups: 3
  maxSize: 500
  maxAge: 30
  compress: true

mysql:
  username: root
  password: 123456ljc
  ip: 127.0.0.1
  port: 3306
  database: bosh-admin
  config: charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 10
  maxOpenConns: 100

pgsql:
  host: 127.0.0.1
  user: postgres
  password: 123456LJC
  dbname: bosh-admin
  port: 5432
  config: 'sslmode=disable TimeZone=Asia/Shanghai'
  maxIdleConns: 10
  maxOpenConns: 100
